### ISSUE TITLE
offsetX and offsetY should be a float

### ISSUE THREAD

**Issue by panthus** [norpan/elm-html5-drag-drop#12]
According to the spec (https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/offsetY) offsetX and offsetY are a float.

They are currently parsed as int so events which contain a float offset are ignored because the decoder fails. 

Took me quite a while to figure out why the drop and dragover events were missing in some cases :)

Something else I noticed when I was tracking this down is that you should also call preventDefault on the dragenter event (for example IE11 requires this before it will fire the dragover and drop event). The spec (https://developer.mozilla.org/en-US/docs/Web/Events/dragenter) states that it will cancel the current target as a drop target if you do not call preventDefault so it makes sense to call it.

**Comment by norpan** [comment]
Yes, I've been trying not to use `offsetX` and `offsetY` at all, since they are relative to the target node, and not the droppable, which makes the numbers wrong when an event has bubbled down to the droppable. However, there is no easy way to get the coordinates without calling functions, which you can't do in a decoder. I guess it's possible to traverse up to the document, calculating stuff using a recursive decoder though.

But yes, decoding using float would be better, I'm just curious when you would get non-integer values.

With regards to dragenter, that's something I've missed that you need to prevent default. They don't do it in the example, and that would also mean that you need to catch that event in order to be able to prevent the default.

However, I see no harm in preventing default on that event. It should also stop propagation so that you only get dragenter for the topmost draggable I suppose.

I'll have a look at it tomorrow!

**Comment by panthus** [comment]
I’m currently not using the position, I managed to make it work by defining dedicated drop zones and using the dropId to arrange highlighting etc (I’m building some kind of kanban board).

I ran into the float values by accident. In FF, Chrome and Edge I get nice integers, but IE11 decided that the offsetY should be a float... Probably some weird layout thing in IE11.

Thanks, for taking a look!

**Comment by norpan** [comment]
I think my commit closed this automatically, please verify that it is fixed!

**Comment by panthus** [comment]
IE11 is fixed in 3.1.2, thanks. 

Google Chrome is still broken though (was introduced in 3.1.1), but this is already handled in #13.
